# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tuxpen.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import sys

import resources_rc
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Tuxpen:
    def setupUi(self, Tuxpen):
        Tuxpen.setObjectName("Tuxpen")
        Tuxpen.resize(458, 446)
        font = QtGui.QFont()
        font.setFamily("DejaVu Serif")
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        Tuxpen.setFont(font)
        Tuxpen.setMouseTracking(True)
        Tuxpen.setFocusPolicy(QtCore.Qt.StrongFocus)
        Tuxpen.setAutoFillBackground(True)
        self.centralwidget = QtWidgets.QWidget(Tuxpen)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setMaximumSize(QtCore.QSize(132, 430))
        self.centralwidget.setAutoFillBackground(False)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setContentsMargins(10, 10, 10, 10)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.main_frame = QtWidgets.QFrame(self.centralwidget)
        self.main_frame.setMaximumSize(QtCore.QSize(132, 430))
        self.main_frame.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0.0890511 rgba(47, 47, 47, 255), stop:0.455474 rgba(31, 31, 31, 255));\n"
                                      "border-radius: 7px;")
        self.main_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.main_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_frame.setObjectName("main_frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.main_frame)
        self.verticalLayout.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.title = QtWidgets.QFrame(self.main_frame)
        self.title.setMaximumSize(QtCore.QSize(16777215, 16))
        self.title.setStyleSheet("background-color: none;")
        self.title.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.title.setFrameShadow(QtWidgets.QFrame.Raised)
        self.title.setObjectName("title")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.title)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.text = QtWidgets.QFrame(self.title)
        self.text.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.text.setFrameShadow(QtWidgets.QFrame.Raised)
        self.text.setObjectName("text")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.text)
        self.verticalLayout_3.setContentsMargins(23, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(self.text)
        font = QtGui.QFont()
        font.setFamily("Inconsolata Expanded Bold")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: none;")
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.verticalLayout_2.addWidget(self.text)
        self.verticalLayout.addWidget(self.title)
        self.body = QtWidgets.QFrame(self.main_frame)
        self.body.setMaximumSize(QtCore.QSize(132, 430))
        self.body.setStyleSheet("background-color: none;")
        self.body.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.body.setFrameShadow(QtWidgets.QFrame.Raised)
        self.body.setObjectName("body")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.body)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame_pen = QtWidgets.QFrame(self.body)
        self.frame_pen.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_pen.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_pen.setObjectName("frame_pen")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_pen)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.button_pen = QtWidgets.QPushButton(self.frame_pen)
        self.button_pen.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_pen.setStyleSheet("QPushButton:hover {\n"
                                      "    background-color: rgb(62, 62, 62);\n"
                                      "}")
        self.button_pen.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/pen.png"),
                       QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_pen.setIcon(icon)
        self.button_pen.setIconSize(QtCore.QSize(24, 24))
        self.button_pen.setObjectName("button_pen")
        self.verticalLayout_8.addWidget(self.button_pen)
        self.verticalLayout_4.addWidget(self.frame_pen)
        self.frame_eraser = QtWidgets.QFrame(self.body)
        self.frame_eraser.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_eraser.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_eraser.setObjectName("frame_eraser")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_eraser)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.button_eraser = QtWidgets.QPushButton(self.frame_eraser)
        self.button_eraser.setCursor(
            QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_eraser.setStyleSheet("QPushButton:hover {\n"
                                         "    background-color: rgb(62, 62, 62);\n"
                                         "}")
        self.button_eraser.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/eraser.png"),
                        QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_eraser.setIcon(icon1)
        self.button_eraser.setIconSize(QtCore.QSize(24, 24))
        self.button_eraser.setObjectName("button_eraser")
        self.verticalLayout_6.addWidget(self.button_eraser)
        self.verticalLayout_4.addWidget(self.frame_eraser)
        self.frame_undo_redo = QtWidgets.QFrame(self.body)
        self.frame_undo_redo.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_undo_redo.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_undo_redo.setObjectName("frame_undo_redo")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_undo_redo)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_undo = QtWidgets.QFrame(self.frame_undo_redo)
        self.frame_undo.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_undo.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_undo.setObjectName("frame_undo")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.frame_undo)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.button_undo = QtWidgets.QPushButton(self.frame_undo)
        self.button_undo.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_undo.setStyleSheet("QPushButton:hover {\n"
                                       "    background-color: rgb(62, 62, 62);\n"
                                       "}")
        self.button_undo.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons/undo.png"),
                        QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_undo.setIcon(icon2)
        self.button_undo.setIconSize(QtCore.QSize(20, 20))
        self.button_undo.setObjectName("button_undo")
        self.verticalLayout_10.addWidget(self.button_undo)
        self.horizontalLayout.addWidget(self.frame_undo)
        self.frame_redo = QtWidgets.QFrame(self.frame_undo_redo)
        self.frame_redo.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_redo.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_redo.setObjectName("frame_redo")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame_redo)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.button_redo = QtWidgets.QPushButton(self.frame_redo)
        self.button_redo.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_redo.setStyleSheet("QPushButton:hover {\n"
                                       "    background-color: rgb(62, 62, 62);\n"
                                       "}")
        self.button_redo.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/icons/redo.png"),
                        QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_redo.setIcon(icon3)
        self.button_redo.setIconSize(QtCore.QSize(20, 20))
        self.button_redo.setObjectName("button_redo")
        self.verticalLayout_9.addWidget(self.button_redo)
        self.horizontalLayout.addWidget(self.frame_redo)
        self.verticalLayout_4.addWidget(self.frame_undo_redo)
        self.frame_clear = QtWidgets.QFrame(self.body)
        self.frame_clear.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_clear.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_clear.setObjectName("frame_clear")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_clear)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.button_clear = QtWidgets.QPushButton(self.frame_clear)
        self.button_clear.setCursor(
            QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_clear.setStyleSheet("QPushButton:hover {\n"
                                        "    background-color: rgb(62, 62, 62);\n"
                                        "}")
        self.button_clear.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/icons/delete.png"),
                        QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_clear.setIcon(icon4)
        self.button_clear.setIconSize(QtCore.QSize(24, 24))
        self.button_clear.setObjectName("button_clear")
        self.verticalLayout_5.addWidget(self.button_clear)
        self.verticalLayout_4.addWidget(self.frame_clear)
        self.frame_exit = QtWidgets.QFrame(self.body)
        self.frame_exit.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_exit.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_exit.setObjectName("frame_exit")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_exit)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.button_exit = QtWidgets.QPushButton(self.frame_exit)
        self.button_exit.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_exit.setStyleSheet("QPushButton:hover {\n"
                                       "    background-color: rgb(62, 62, 62);\n"
                                       "}")
        self.button_exit.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/icons/close.png"),
                        QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_exit.setIcon(icon5)
        self.button_exit.setIconSize(QtCore.QSize(24, 24))
        self.button_exit.setObjectName("button_exit")
        self.verticalLayout_7.addWidget(self.button_exit)
        self.verticalLayout_4.addWidget(self.frame_exit)
        self.verticalLayout.addWidget(self.body)
        self.color_box = QtWidgets.QFrame(self.main_frame)
        self.color_box.setMaximumSize(QtCore.QSize(16777215, 128))
        self.color_box.setStyleSheet("background-color: none;")
        self.color_box.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.color_box.setFrameShadow(QtWidgets.QFrame.Raised)
        self.color_box.setObjectName("color_box")
        self.gridLayout = QtWidgets.QGridLayout(self.color_box)
        self.gridLayout.setContentsMargins(5, 3, 3, 3)
        self.gridLayout.setObjectName("gridLayout")
        self.colors = QtWidgets.QFrame(self.color_box)
        self.colors.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.colors.setFrameShadow(QtWidgets.QFrame.Raised)
        self.colors.setObjectName("colors")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.colors)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.color_white = QtWidgets.QPushButton(self.colors)
        self.color_white.setMaximumSize(QtCore.QSize(27, 27))
        self.color_white.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.color_white.setStyleSheet("QPushButton {\n"
                                       "    border: none;\n"
                                       "    border-radius: 12px;\n"
                                       "    background-color: rgb(230, 230, 230);\n"
                                       "}\n"
                                       "\n"
                                       "QPushButton:hover {\n"
                                       "    border-radius: 2px;\n"
                                       "}")
        self.color_white.setText("")
        self.color_white.setObjectName("color_white")
        self.gridLayout_2.addWidget(self.color_white, 0, 0, 1, 1)
        self.color_black = QtWidgets.QPushButton(self.colors)
        self.color_black.setMaximumSize(QtCore.QSize(27, 27))
        self.color_black.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.color_black.setStyleSheet("QPushButton {\n"
                                       "    border: none;\n"
                                       "    border-radius: 12px;\n"
                                       "    background-color: rgb(98, 98, 98);\n"
                                       "}\n"
                                       "\n"
                                       "QPushButton:hover {\n"
                                       "    border-radius: 2px;\n"
                                       "}")
        self.color_black.setText("")
        self.color_black.setObjectName("color_black")
        self.gridLayout_2.addWidget(self.color_black, 0, 1, 1, 1)
        self.color_red = QtWidgets.QPushButton(self.colors)
        self.color_red.setMaximumSize(QtCore.QSize(27, 27))
        self.color_red.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.color_red.setStyleSheet("QPushButton {\n"
                                     "    border: none;\n"
                                     "    border-radius: 12px;\n"
                                     "    background-color: rgb(255, 6, 81);\n"
                                     "}\n"
                                     "\n"
                                     "QPushButton:hover {\n"
                                     "    border-radius: 2px;\n"
                                     "}")
        self.color_red.setText("")
        self.color_red.setObjectName("color_red")
        self.gridLayout_2.addWidget(self.color_red, 1, 0, 1, 1)
        self.color_green = QtWidgets.QPushButton(self.colors)
        self.color_green.setMaximumSize(QtCore.QSize(27, 27))
        self.color_green.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.color_green.setStyleSheet("QPushButton {\n"
                                       "    border: none;\n"
                                       "    border-radius: 12px;\n"
                                       "    background-color: rgb(75, 213, 0);\n"
                                       "}\n"
                                       "\n"
                                       "QPushButton:hover {\n"
                                       "    border-radius: 2px;\n"
                                       "}")
        self.color_green.setText("")
        self.color_green.setObjectName("color_green")
        self.gridLayout_2.addWidget(self.color_green, 1, 1, 1, 1)
        self.color_blue = QtWidgets.QPushButton(self.colors)
        self.color_blue.setMaximumSize(QtCore.QSize(27, 27))
        self.color_blue.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.color_blue.setStyleSheet("QPushButton {\n"
                                      "    border: none;\n"
                                      "    border-radius: 12px;\n"
                                      "    background-color: rgb(2, 85, 173);\n"
                                      "}\n"
                                      "\n"
                                      "QPushButton:hover {\n"
                                      "    border-radius: 2px;\n"
                                      "}")
        self.color_blue.setText("")
        self.color_blue.setObjectName("color_blue")
        self.gridLayout_2.addWidget(self.color_blue, 2, 0, 1, 1)
        self.color_yellow = QtWidgets.QPushButton(self.colors)
        self.color_yellow.setMaximumSize(QtCore.QSize(27, 27))
        self.color_yellow.setCursor(
            QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.color_yellow.setStyleSheet("QPushButton {\n"
                                        "    border: none;\n"
                                        "    border-radius: 12px;\n"
                                        "    background-color: rgb(255, 226, 5);\n"
                                        "}\n"
                                        "\n"
                                        "QPushButton:hover {\n"
                                        "    border-radius: 2px;\n"
                                        "}")
        self.color_yellow.setText("")
        self.color_yellow.setObjectName("color_yellow")
        self.gridLayout_2.addWidget(self.color_yellow, 2, 1, 1, 1)
        self.gridLayout.addWidget(self.colors, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.color_box)
        self.horizontalLayout_2.addWidget(self.main_frame)
        Tuxpen.setCentralWidget(self.centralwidget)

        self.retranslateUi(Tuxpen)
        QtCore.QMetaObject.connectSlotsByName(Tuxpen)
        Tuxpen.setTabOrder(self.button_pen, self.button_eraser)
        Tuxpen.setTabOrder(self.button_eraser, self.button_clear)
        Tuxpen.setTabOrder(self.button_clear, self.button_exit)
        Tuxpen.setTabOrder(self.button_exit, self.color_white)
        Tuxpen.setTabOrder(self.color_white, self.color_black)
        Tuxpen.setTabOrder(self.color_black, self.color_red)
        Tuxpen.setTabOrder(self.color_red, self.color_green)
        Tuxpen.setTabOrder(self.color_green, self.color_blue)
        Tuxpen.setTabOrder(self.color_blue, self.color_yellow)

    def retranslateUi(self, Tuxpen):
        _translate = QtCore.QCoreApplication.translate
        Tuxpen.setWindowTitle(_translate("Tuxpen", "Tuxpen"))
        self.label.setText(_translate("Tuxpen", "Tuxpen"))
        self.label.setStyleSheet("color: #fff;")
